### ISSUE TITLE
Question about font style transfer

### ISSUE THREAD

**Issue by hahaha221** [gttugsuu/Contained-Neural-Style-Transfer-for-Decorated-Logo-Generation#1]
Excuse me, is it possible to use your model to transfer the font style for the alphabet?

**Comment by gttugsuu** [comment]
I think you should refer to the papers: [Neural Font Style Transfer](https://www.researchgate.net/publication/322780401_Neural_Font_Style_Transfer), [Constrained Neural Style Transfer for Decorated Logo Generation](https://arxiv.org/pdf/1803.00686.pdf).
