### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by mjmikulski** [gttugsuu/Contained-Neural-Style-Transfer-for-Decorated-Logo-Generation#2]
An interesting concept and nice work. I would like to reuse your code but without a license I am not sure if you agree and to what extent. 

Could you add a licence to the repository?

A comprehensive info about licenses can be found [here](https://choosealicense.com/), [this one](https://choosealicense.com/licenses/mit/) is often used for this kind of projects. It is enough to copy the text and put in `LICENSE` file in the main dir.

**Comment by gttugsuu** [comment]
@mjmikulski Thanks for pointing out. I added MIT license. Feel free to use the code for your projects and distribute :)

**Comment by mjmikulski** [comment]
Perfect, thank you! :)
